# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: "11"
#      - name: set up JDK 11
#      - uses: actions/setup-java@v1
#          with:
#            java-version: '11'
#            distribution: 'adopt'
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

#       - name: Record Time
#         id: time
#         uses: JantHsueh/get-time-action@master
#         with:
#           timeZone: 8

#       - name: Get git log
#         id: git_log
#         uses: JantHsueh/get-git-log-action@master
#         with:
#           tag: v1.0.2

#       - name: Preparing DEV APK
#         id: dev_apk
#         uses: JantHsueh/get-apk-info-action@master
#         with:
#           apkPath: app/build/outputs/apk/dev/release/com.polestar.china.android-dev-debug.apk

      - name: Uploading Dev to Pgyer
        uses: JantHsueh/upload-file-action@master
        with:
          url: https://www.pgyer.com/apiv2/app/upload
          method: POST
          forms: '{"_api_key":"${{ secrets.P_API_KEY }}", "buildInstallType":2, "userKey": "${{ secrets.POLESTAR_PGYER_USER_KEY }}", "buildPassword": "${{ secrets.POLESTAR_PGYER_BUILD_PASSWORD }}"}'
          fileForms: '{"file":"app/build/outputs/apk/debug/app-debug.apk"}'

      - name: Generate QR Code
        uses: SnowCait/qrcode@v1.0.0
        with:
          text: https://www.pgyer.com/DC2R
          path: qrcode.png

