name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

     - name: Upload APK
       uses: actions/upload-artifact@v1
       with:
         name: app
         path: app/build/outputs/apk/debug/xw-debug.apk

      # step：向蒲公英上传文件
#      - name: Upload To Pgyer
#        uses: JantHsueh/upload-file-action@master
#        with:
#          url: https://www.pgyer.com/apiv2/app/upload
#          method: POST
#          forms: '{"_api_key":"${{ secrets.P_API_KEY }}","buildInstallType":3}'
#          fileForms: '{"file":"app/build/outputs/apk/debug/xw-debug.apk"}'
